---
name: "ESP-IDF C/C++ Lint"
description: "clang-format + clang-tidy via cpp-linter"
inputs:
  paths:
    description: "Comma-separated globs to lint"
    required: false
    default: "src/**,inc/**,examples/**"
  clang_version:
    description: "Clang major version"
    required: false
    default: "20"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Run C/C++ linters
      uses: cpp-linter/cpp-linter-action@v2
      with:
        style: 'file'
        tidy-checks: ''
        version: ${{ inputs.clang_version }}
        files-changed-only: false
        lines-changed-only: false
        file-annotations: true
        extensions: 'c,cpp,cc,cxx,h,hpp'
        ignore: 'build|.git'
        path: ${{ inputs.paths }}
