---
name: "Setup CI Build Workspace"
description: "Run project's setup_ci.sh to stage a clean workspace"
inputs:
  project-path:
    description: "Path to the project (contains scripts/)"
    required: true
  build-dir:
    description: "Staging/build directory name"
    required: true
  script-path:
    description: >
      Path to setup_ci.sh (default: <project-path>/scripts/setup_ci.sh)
    required: false
runs:
  using: "composite"
  steps:
    - name: Make setup script executable
      shell: bash
      run: |
        SCRIPT_PATH="${{ inputs.script-path }}"
        if [ -z "$SCRIPT_PATH" ]; then
          SCRIPT_PATH="${{ inputs.project-path }}/scripts/setup_ci.sh"
        fi
        chmod +x "$SCRIPT_PATH"

    - name: Run setup_ci.sh
      shell: bash
      run: |
        set -e
        SCRIPT_PATH="${{ inputs.script-path }}"
        if [ -z "$SCRIPT_PATH" ]; then
          SCRIPT_PATH="${{ inputs.project-path }}/scripts/setup_ci.sh"
        fi
        "$SCRIPT_PATH" "${{ inputs.build-dir }}"
        test -d "${{ inputs.build-dir }}" || { \
          echo "Missing build dir"; exit 1; }
