---
name: "Ensure Tools Directory Present"
description: "Clone or validate the presence of project tools directory"
inputs:
  project_tools_dir:
    description: >
      Path to project tools directory (contains scripts directly).
      Leave empty to auto-detect.
    required: false
  project_dir:
    description: "Path to the ESP-IDF project (contains CMakeLists.txt)"
    required: false
    default: "."
  auto_clone_tools:
    description: "Auto-clone tools repo if project_tools_dir is missing"
    required: false
    default: "true"
outputs:
  project_tools_path:
    description: "Resolved path to the project tools directory"
    value: ${{ steps.resolve.outputs.project_tools_path }}
runs:
  using: "composite"
  steps:
    - name: Resolve and ensure tools directory
      id: resolve
      shell: bash
      run: |
        set -e
        
        # Use hardcoded trusted repository URL and main branch
        TOOLS_REPO_URL="https://github.com/N3b3x/hf-espidf-project-tools.git"
        TOOLS_BRANCH="main"
        TOOLS_DIR_NAME=$(basename "${TOOLS_REPO_URL}" .git)
        echo "Tools directory name: ${TOOLS_DIR_NAME}"
        
        # Resolve project tools path using consistent logic
        if [ -n "${{ inputs.project_tools_dir }}" ]; then
          # Handle both absolute and relative paths
          if [[ "${{ inputs.project_tools_dir }}" == /* ]]; then
            SCRIPTS_PATH="${{ inputs.project_tools_dir }}"
          else
            SCRIPTS_PATH="$(pwd)/${{ inputs.project_tools_dir }}"
          fi
        else
          if [ -d "${{ inputs.project_dir }}/${TOOLS_DIR_NAME}" ]; then
            SCRIPTS_PATH="$(pwd)/${{ inputs.project_dir }}/${TOOLS_DIR_NAME}"
          else
            SCRIPTS_PATH="$(pwd)/${TOOLS_DIR_NAME}"
          fi
        fi

        echo "Resolved project tools path: ${SCRIPTS_PATH}"
        
        # Also resolve project directory path to absolute
        if [[ "${{ inputs.project_dir }}" == /* ]]; then
          PROJECT_PATH="${{ inputs.project_dir }}"
        else
          PROJECT_PATH="$(pwd)/${{ inputs.project_dir }}"
        fi
        echo "Resolved project path: ${PROJECT_PATH}"
        
        # Clone if directory doesn't exist and auto_clone_tools is true
        if [ ! -d "${SCRIPTS_PATH}" ] && [ "${{ inputs.auto_clone_tools }}" = "true" ]; then
          echo "Cloning tools repo to ${SCRIPTS_PATH}"
          
          # Security: Using hardcoded trusted repository URL and main branch
          echo "Cloning from trusted source: ${TOOLS_REPO_URL} (${TOOLS_BRANCH} branch)"
          git clone --depth 1 --branch "${TOOLS_BRANCH}" \
            "${TOOLS_REPO_URL}" "${SCRIPTS_PATH}"
        elif [ ! -d "${SCRIPTS_PATH}" ]; then
          echo "ERROR: Project tools directory not found at ${SCRIPTS_PATH}" >&2
          echo "Available directories:" >&2
          ls -la . || true
          ls -la "${PROJECT_PATH}" || true
          exit 1
        else
          echo "Tools directory exists: ${SCRIPTS_PATH}"
        fi

        # Validate required scripts exist
        REQUIRED_SCRIPTS=("generate_matrix.py" "build_app.sh" "config_loader.sh")
        for script in "${REQUIRED_SCRIPTS[@]}"; do
          if [ ! -f "${SCRIPTS_PATH}/${script}" ]; then
            echo "ERROR: Required script '${script}' not found in ${SCRIPTS_PATH}" >&2
            echo "Available scripts:" >&2
            ls -la "${SCRIPTS_PATH}" || true
            exit 1
          else
            echo "✓ Found ${script}"
          fi
        done

        echo "✓ All required scripts found in ${SCRIPTS_PATH}"
        echo "project_tools_path=${SCRIPTS_PATH}" >> "$GITHUB_OUTPUT"
