name: Build

on:
  workflow_call:
    inputs:
      max_dec_total:
        description: >
          Maximum allowed firmware size (in bytes) to enforce size budgets.
        type: number
        default: 1600000  # Default is 1.6 MB

jobs:
  size-report:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce size budgets (optional)
        if: always()
        shell: bash
        env:
          MAX_DEC_TOTAL: ${{ inputs.max_dec_total }}
        run: |
          set -euo pipefail
          vio=0
          while IFS= read -r -d '' st; do
            dec=$(grep -E '^\\s*text\\\s+data\\\s+bss\\\s+dec' -A1 "$st" | \
                  tail -1 | awk '{print $4}' || echo 0)
            dir="$(dirname "$st")"
            if [[ "${dec:-0}" -gt "$MAX_DEC_TOTAL" ]]; then
              echo "::error file=${st}::${dir} dec=${dec} exceeds MAX_DEC_TOTAL=${MAX_DEC_TOTAL}"
              vio=$((vio+1))
            fi
          done < <(find fw_artifacts -type f -name "size.txt" -print0)
          [[ $vio -gt 0 ]] && exit 1 || exit 0
