---
name: Docs Build & Deploy (Reusable)

on:
  workflow_call:
    inputs:
      project_dir:
        description: "Path containing Doxyfile and sources"
        type: string
        required: true
      project_tools_dir:
        description: >
          Path to project tools directory (contains scripts directly).
          Leave empty to auto-detect. Only needed if using scripts dir outside of project dir or project-specific tools.
        type: string
        required: false
      doxygen_config:
        description: "Path to Doxyfile (relative to repo root)"
        type: string
        default: "Doxyfile"
      output_dir:
        description: "Generated HTML dir (relative to repo root)"
        type: string
        default: "docs/doxygen/html"
      run_link_check:
        description: "Run documentation link checker"
        type: boolean
        default: true
      link_check_paths:
        description: "Comma-separated paths to check for broken links"
        type: string
        default: "docs/**,*.md,**/docs/**"
      auto_clone_tools:
        description: "Auto-clone tools repo if project_tools_dir is missing (only needed for project-specific tools)"
        type: boolean
        default: false
      tools_repo_url:
        description: "Git URL for project tools repository (optional, uses default if not specified)"
        type: string
        required: false
      tools_repo_ref:
        description: "Branch or tag for project tools repository (optional, uses default if not specified)"
        type: string
        required: false
      tools_repo_sha:
        description: "Specific commit SHA for project tools repository (most secure option)"
        type: string
        required: false
      deploy_pages:
        description: "Deploy to GitHub Pages (main branch, non-PR)"
        type: boolean
        default: true
    secrets:
      GITHUB_TOKEN:
        required: false

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure tools directory present (if needed)
        if: ${{ inputs.auto_clone_tools || inputs.project_tools_dir }}
        id: tools-validate
        uses: ./.github/actions/ensure-tools-directory
        with:
          project_tools_dir: ${{ inputs.project_tools_dir }}
          project_dir: ${{ inputs.project_dir }}
          auto_clone_tools: ${{ inputs.auto_clone_tools }}
          tools_repo_url: ${{ inputs.tools_repo_url }}
          tools_repo_ref: ${{ inputs.tools_repo_ref }}
          tools_repo_sha: ${{ inputs.tools_repo_sha }}

      - name: Check documentation links
        if: ${{ inputs.run_link_check }}
        uses: AlexanderDokuchaev/md-dead-link-check@v1.2.0

      - name: Install Doxygen + Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Build docs (Doxygen)
        run: |
          cd "${{ inputs.project_dir }}"
          doxygen "${{ inputs.doxygen_config }}"
          test -d "${{ inputs.output_dir }}" || { \
            echo "No docs at ${{ inputs.output_dir }}"; exit 1; }

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: ${{ inputs.output_dir }}
          retention-days: 7

      - name: Deploy to GitHub Pages
        if: >
          ${{ inputs.deploy_pages && github.ref == 'refs/heads/main' &&
          github.event_name != 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ inputs.output_dir }}
          force_orphan: true
