---
name: Docs Build & Deploy (Reusable)

on:
  workflow_call:
    inputs:
      doxygen_config:
        description: "Path to Doxyfile (relative to repo root)"
        type: string
        default: "Doxyfile"
      output_dir:
        description: "Generated HTML dir (relative to repo root)"
        type: string
        default: "docs/doxygen/html"
      run_link_check:
        description: "Run documentation link checker"
        type: boolean
        default: true
      link_check_paths:
        description: "Comma-separated paths to check for broken links"
        type: string
        default: "docs/**,*.md,**/docs/**"
      run_markdown_lint:
        description: "Run markdown linting on documentation files"
        type: boolean
        default: false
      markdown_lint_paths:
        description: "Glob patterns for markdown files to lint"
        type: string
        default: "**/*.md"
      run_spell_check:
        description: "Run spell checking on documentation files"
        type: boolean
        default: false
      spell_check_paths:
        description: "Glob patterns for files to spell check"
        type: string
        default: "**/*.md"
      spell_check_config:
        description: "Path to cspell configuration file"
        type: string
        default: ".cspell.json"
      deploy_pages:
        description: "Deploy to GitHub Pages (main branch, non-PR)"
        type: boolean
        default: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check documentation links
        if: ${{ inputs.run_link_check }}
        uses: AlexanderDokuchaev/md-dead-link-check@v1.2.0
        with:
          paths: ${{ inputs.link_check_paths }}

      - name: Setup Node.js (for linting)
        if: ${{ inputs.run_markdown_lint || inputs.run_spell_check }}
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install markdownlint
        if: ${{ inputs.run_markdown_lint }}
        run: npm install -g markdownlint-cli

      - name: Lint markdown files
        if: ${{ inputs.run_markdown_lint }}
        run: markdownlint "${{ inputs.markdown_lint_paths }}" --ignore node_modules

      - name: Install cspell
        if: ${{ inputs.run_spell_check }}
        run: npm install -g cspell

      - name: Spell check
        if: ${{ inputs.run_spell_check }}
        run: |
          if [ -f "${{ inputs.spell_check_config }}" ]; then
            cspell "${{ inputs.spell_check_paths }}" --config "${{ inputs.spell_check_config }}"
          else
            cspell "${{ inputs.spell_check_paths }}"
          fi

      - name: Install Doxygen + Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Build docs (Doxygen)
        run: |
          doxygen "${{ inputs.doxygen_config }}"
          test -d "${{ inputs.output_dir }}" || { \
            echo "No docs at ${{ inputs.output_dir }}"; exit 1; }

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: ${{ inputs.output_dir }}
          retention-days: 7

      - name: Deploy to GitHub Pages
        if: >
          ${{ inputs.deploy_pages && github.ref == 'refs/heads/main' &&
          github.event_name != 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ inputs.output_dir }}
          force_orphan: true
