---
name: C/C++ Lint (Reusable)

on:
  workflow_call:
    inputs:
      paths:
        description: "Comma-separated globs to lint"
        type: string
        default: "src/**,inc/**,examples/**"
      clang_version:
        description: "Clang major version"
        type: string
        default: "20"
    secrets:
      GITHUB_TOKEN:
        required: false

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run lint
        uses: ./.github/actions/espidf-lint
        with:
          paths: ${{ inputs.paths }}
          clang_version: ${{ inputs.clang_version }}
